### ISSUE TITLE
Long config section is not parsed correctly

### ISSUE THREAD

**Issue by mihaipopescu** [editorconfig/editorconfig-core-net#3]
Could this https://github.com/editorconfig/editorconfig-visualstudio/issues/21 be an issue of Core ?

**Comment by Mpdreamz** [comment]
The released version of the extension does not used the managed .NET core:

https://github.com/editorconfig/editorconfig-visualstudio/pull/22

It still uses the C version which has limits on sections, properties and values.

The `master` on editorconfig-visual-studio` is unreleased sadly. It solves several issues but also introduces several others. Since VS2017 and up ship with EditorConfig build in and I personally do all my development on Rider (which uses this managed core implentation) I have no vested interest in continuing supporting the VS extension.

I've added a test for this and this does not occur in this managed version.
